version: '3.1'

services:

  db:
    container_name: django_start_db_1
    image: postgres:12-alpine
    ports: 
      - 5432:5432
    env_file:
      - .env

  redis:
    container_name: django_start_redis_1
    image: redis:alpine
    ports:
      - 6379:6379
    env_file:
      - .env
